### ISSUE TITLE
new problem with new commite - vboxpower user have no permision to action

### ISSUE THREAD

**Issue by RABBITERMAN** [ssbostan/vboxpower#7]
in this vboxpower version i can't use it ,because it do not give response.i think that new user have not enough permission..

**Comment by miladhashemi** [comment]
Hi @RABBITERMAN 
Please share the error you got with me.

**Comment by RABBITERMAN** [comment]
i have not see any error,just when i call web service take time and no any responce!

**Comment by miladhashemi** [comment]
I did a fresh install again everything is OK and working.

Also, I have checked the code added to the [`deploy`](https://github.com/ssbostan/vboxpower/blob/master/deploy) script file again:
```bash
if [ $(getent passwd vboxpower) ]; then
    echo "INFO: vboxpower user already exists."
else
    useradd -Mr vboxpower
    echo "INFO: vboxpower user created successfully."
fi
```
It simply adds a vboxpower system user if it doesn't exist.

Finaly username used in [`vboxpower.service`](https://github.com/ssbostan/vboxpower/blob/master/vboxpower.service) file as user entry:

```bash
User=vboxpower
```

**Comment by ssbostan** [comment]
I reverted that change and will check it soon.
